//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
using ACS.TouristTicket.Model;

namespace ACS.TouristTicket.DataAccess
{
    public partial class TouristTicketEntities : ObjectContext
    {
        public const string ConnectionString = "name=TouristTicketEntities";
        public const string ContainerName = "TouristTicketEntities";
    
        #region Constructors
    
        public TouristTicketEntities()
            : base(ConnectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public TouristTicketEntities(string connectionString)
            : base(connectionString, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        public TouristTicketEntities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            this.ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<tbClientUploadDownloadLog> tbClientUploadDownloadLogs
        {
            get { return _tbClientUploadDownloadLogs  ?? (_tbClientUploadDownloadLogs = CreateObjectSet<tbClientUploadDownloadLog>("tbClientUploadDownloadLogs")); }
        }
        private ObjectSet<tbClientUploadDownloadLog> _tbClientUploadDownloadLogs;
    
        public ObjectSet<tbCode> tbCodes
        {
            get { return _tbCodes  ?? (_tbCodes = CreateObjectSet<tbCode>("tbCodes")); }
        }
        private ObjectSet<tbCode> _tbCodes;
    
        public ObjectSet<tbCodeCategory> tbCodeCategories
        {
            get { return _tbCodeCategories  ?? (_tbCodeCategories = CreateObjectSet<tbCodeCategory>("tbCodeCategories")); }
        }
        private ObjectSet<tbCodeCategory> _tbCodeCategories;
    
        public ObjectSet<tbCounter> tbCounters
        {
            get { return _tbCounters  ?? (_tbCounters = CreateObjectSet<tbCounter>("tbCounters")); }
        }
        private ObjectSet<tbCounter> _tbCounters;
    
        public ObjectSet<tbDownloadLog> tbDownloadLogs
        {
            get { return _tbDownloadLogs  ?? (_tbDownloadLogs = CreateObjectSet<tbDownloadLog>("tbDownloadLogs")); }
        }
        private ObjectSet<tbDownloadLog> _tbDownloadLogs;
    
        public ObjectSet<tbExceptionLog> tbExceptionLogs
        {
            get { return _tbExceptionLogs  ?? (_tbExceptionLogs = CreateObjectSet<tbExceptionLog>("tbExceptionLogs")); }
        }
        private ObjectSet<tbExceptionLog> _tbExceptionLogs;
    
        public ObjectSet<tbRole> tbRoles
        {
            get { return _tbRoles  ?? (_tbRoles = CreateObjectSet<tbRole>("tbRoles")); }
        }
        private ObjectSet<tbRole> _tbRoles;
    
        public ObjectSet<tbSampleTable> tbSampleTables
        {
            get { return _tbSampleTables  ?? (_tbSampleTables = CreateObjectSet<tbSampleTable>("tbSampleTables")); }
        }
        private ObjectSet<tbSampleTable> _tbSampleTables;
    
        public ObjectSet<tbSetting> tbSettings
        {
            get { return _tbSettings  ?? (_tbSettings = CreateObjectSet<tbSetting>("tbSettings")); }
        }
        private ObjectSet<tbSetting> _tbSettings;
    
        public ObjectSet<tbTicket> tbTickets
        {
            get { return _tbTickets  ?? (_tbTickets = CreateObjectSet<tbTicket>("tbTickets")); }
        }
        private ObjectSet<tbTicket> _tbTickets;
    
        public ObjectSet<tbTicketActivationLog> tbTicketActivationLogs
        {
            get { return _tbTicketActivationLogs  ?? (_tbTicketActivationLogs = CreateObjectSet<tbTicketActivationLog>("tbTicketActivationLogs")); }
        }
        private ObjectSet<tbTicketActivationLog> _tbTicketActivationLogs;
    
        public ObjectSet<tbTicketInZone> tbTicketInZones
        {
            get { return _tbTicketInZones  ?? (_tbTicketInZones = CreateObjectSet<tbTicketInZone>("tbTicketInZones")); }
        }
        private ObjectSet<tbTicketInZone> _tbTicketInZones;
    
        public ObjectSet<tbTicketLog> tbTicketLogs
        {
            get { return _tbTicketLogs  ?? (_tbTicketLogs = CreateObjectSet<tbTicketLog>("tbTicketLogs")); }
        }
        private ObjectSet<tbTicketLog> _tbTicketLogs;
    
        public ObjectSet<tbTicketSetting> tbTicketSettings
        {
            get { return _tbTicketSettings  ?? (_tbTicketSettings = CreateObjectSet<tbTicketSetting>("tbTicketSettings")); }
        }
        private ObjectSet<tbTicketSetting> _tbTicketSettings;
    
        public ObjectSet<tbTicketUnused> tbTicketUnuseds
        {
            get { return _tbTicketUnuseds  ?? (_tbTicketUnuseds = CreateObjectSet<tbTicketUnused>("tbTicketUnuseds")); }
        }
        private ObjectSet<tbTicketUnused> _tbTicketUnuseds;
    
        public ObjectSet<tbTicketUsage> tbTicketUsages
        {
            get { return _tbTicketUsages  ?? (_tbTicketUsages = CreateObjectSet<tbTicketUsage>("tbTicketUsages")); }
        }
        private ObjectSet<tbTicketUsage> _tbTicketUsages;
    
        public ObjectSet<tbTicketUsageLog> tbTicketUsageLogs
        {
            get { return _tbTicketUsageLogs  ?? (_tbTicketUsageLogs = CreateObjectSet<tbTicketUsageLog>("tbTicketUsageLogs")); }
        }
        private ObjectSet<tbTicketUsageLog> _tbTicketUsageLogs;
    
        public ObjectSet<tbTransactionLog> tbTransactionLogs
        {
            get { return _tbTransactionLogs  ?? (_tbTransactionLogs = CreateObjectSet<tbTransactionLog>("tbTransactionLogs")); }
        }
        private ObjectSet<tbTransactionLog> _tbTransactionLogs;
    
        public ObjectSet<tbUser> tbUsers
        {
            get { return _tbUsers  ?? (_tbUsers = CreateObjectSet<tbUser>("tbUsers")); }
        }
        private ObjectSet<tbUser> _tbUsers;
    
        public ObjectSet<tbUserAccessLog> tbUserAccessLogs
        {
            get { return _tbUserAccessLogs  ?? (_tbUserAccessLogs = CreateObjectSet<tbUserAccessLog>("tbUserAccessLogs")); }
        }
        private ObjectSet<tbUserAccessLog> _tbUserAccessLogs;
    
        public ObjectSet<tbUserInRole> tbUserInRoles
        {
            get { return _tbUserInRoles  ?? (_tbUserInRoles = CreateObjectSet<tbUserInRole>("tbUserInRoles")); }
        }
        private ObjectSet<tbUserInRole> _tbUserInRoles;
    
        public ObjectSet<tbWebUser> tbWebUsers
        {
            get { return _tbWebUsers  ?? (_tbWebUsers = CreateObjectSet<tbWebUser>("tbWebUsers")); }
        }
        private ObjectSet<tbWebUser> _tbWebUsers;
    
        public ObjectSet<tbZoneGroup> tbZoneGroups
        {
            get { return _tbZoneGroups  ?? (_tbZoneGroups = CreateObjectSet<tbZoneGroup>("tbZoneGroups")); }
        }
        private ObjectSet<tbZoneGroup> _tbZoneGroups;
    
        public ObjectSet<tbZone> tbZones
        {
            get { return _tbZones  ?? (_tbZones = CreateObjectSet<tbZone>("tbZones")); }
        }
        private ObjectSet<tbZone> _tbZones;
    
        public ObjectSet<tbZoneAndZoneGroup> tbZoneAndZoneGroups
        {
            get { return _tbZoneAndZoneGroups  ?? (_tbZoneAndZoneGroups = CreateObjectSet<tbZoneAndZoneGroup>("tbZoneAndZoneGroups")); }
        }
        private ObjectSet<tbZoneAndZoneGroup> _tbZoneAndZoneGroups;

        #endregion
    }
}
