//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ACS.TouristTicket.Model
{
    [DataContract(IsReference = true)]
    public partial class tbZoneAndZoneGroup
    {
        #region Primitive Properties
        [DataMember]
        public virtual int PKID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ZoneGroupID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int ZoneID
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> CreatedBy
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> CreatedDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> ModifiedBy
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> ModifiedDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> LastUploadedDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<System.DateTime> LastDownloadedDate
        {
            get;
            set;
        }

        #endregion
    }
}
