//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ACS.TouristTicket.Model
{
    [DataContract(IsReference = true)]
    public partial class TicketDetail
    {
        #region Primitive Properties
        [DataMember]
        public virtual int PKID
        {
            get;
            set;
        }
        [DataMember]
        public virtual decimal Price
        {
            get;
            set;
        }
        [DataMember]
        public virtual string TicketStatus
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ZoneGroupName
        {
            get;
            set;
        }
        [DataMember]
        public virtual System.DateTime CreatedDate
        {
            get;
            set;
        }
        [DataMember]
        public virtual string UserID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int AllowedUsage
        {
            get;
            set;
        }
        [DataMember]
        public virtual int AllowedDays
        {
            get;
            set;
        }

        #endregion
    }
}
