//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ACS.TouristTicket.Model
{
    [DataContract(IsReference = true)]
    public partial class UserInRole
    {
        #region Primitive Properties
        [DataMember]
        public virtual int PKID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string UserID
        {
            get;
            set;
        }
        [DataMember]
        public virtual int RoleID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string RoleName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string RoleDescription
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Password
        {
            get;
            set;
        }
        [DataMember]
        public virtual string DisplayName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Status
        {
            get;
            set;
        }
        [DataMember]
        public virtual int UserPKID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Position
        {
            get;
            set;
        }

        #endregion
    }
}
