//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.Runtime.Serialization;

namespace ACS.TouristTicket.Model
{
    [DataContract(IsReference = true)]
    public partial class ZoneAndZoneGroup
    {
        #region Primitive Properties
        [DataMember]
        public virtual string ZoneID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ZoneName
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ZoneGroupID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string ZoneGroupName
        {
            get;
            set;
        }
        [DataMember]
        public virtual int PKID
        {
            get;
            set;
        }
        [DataMember]
        public virtual Nullable<int> LinkID
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Address
        {
            get;
            set;
        }
        [DataMember]
        public virtual string Phone
        {
            get;
            set;
        }
        [DataMember]
        public virtual string InCharge
        {
            get;
            set;
        }

        #endregion
    }
}
